analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3470969,"name"\:"OrangeHRM Trial \#3470969","teamId"\:3456131,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3492787,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3456131,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
