<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Multiplicar</name>
   <tag></tag>
   <elementGuidId>6b2cb085-3e63-4b77-87d8-559d8135600c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[onclick=&quot;calcular\(\'\*\'\)&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@onclick = 'calcular('*')']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Multiplicar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c6f4f5c5-215c-420a-bfda-3fbcb0ebd20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7f3fd953-acd8-4660-aede-329676654185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>calcular('*')</value>
      <webElementGuid>319e239a-666c-48c3-83b9-352c67907386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Multiplicar</value>
      <webElementGuid>1c93903b-0257-4397-a69b-82258654db72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-152a8ba9b90f3c81842ba94c8b31321f</value>
      <webElementGuid>0de6e16a-2b1b-4fbb-95ca-eef377ccf903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@onclick = 'calcular('*')']</value>
      <webElementGuid>f039b892-27cb-440d-b55f-cc7e511a0ab2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@onclick = 'calcular('*')']</value>
      <webElementGuid>dd414afd-641c-4c26-8062-d73a92bf91ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Multiplicar' or . = 'Multiplicar')]</value>
      <webElementGuid>e871f580-a471-446a-b7cc-274a882abafb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
