<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Somar</name>
   <tag></tag>
   <elementGuidId>9e5f2b99-5e39-4f70-b044-e5c9a27cf5a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[onclick=&quot;calcular\(\'\+\'\)&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@onclick = 'calcular('+')']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Somar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e977413-6951-473b-abcb-1ab67d3740a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d771e7b5-fe77-4870-ac93-278cf2ca5041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>calcular('+')</value>
      <webElementGuid>471c3715-6f47-4e95-89b1-5b8645e11beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Somar</value>
      <webElementGuid>6d0c18e6-0018-407a-9e3d-c58d0bcefaaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fbd63a124dd6ebeccfb51c11ff204def</value>
      <webElementGuid>cb8a4c81-0b19-4ec8-8975-75e791022be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@onclick = 'calcular('+')']</value>
      <webElementGuid>74cdbbef-44e2-4b12-9249-6c8d0cf050fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@onclick = 'calcular('+')']</value>
      <webElementGuid>d0d6a704-68b3-4b26-aa59-6f1bed4d2b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Somar' or . = 'Somar')]</value>
      <webElementGuid>08e6a776-3ad7-4fc6-8c0f-863db42ea269</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
